services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: mkrepo
      POSTGRES_PASSWORD: mkrepo
      POSTGRES_DB: mkrepo
    ports:
      - "5432:5432"
    volumes:
      - mkrepo-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mkrepo@mkrepo.dev
      PGADMIN_DEFAULT_PASSWORD: mkrepo
    ports:
      - "5050:80"

volumes:
  mkrepo-postgres:
