services:
  db:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: mkrepo
      POSTGRES_USER: mkrepo
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
