version: '3'

dotenv: [.env]

tasks:
  default:
    desc: Show this help
    silent: true
    aliases: [help, h]
    cmds:
      - task -l --sort none

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...
      - go tool sqlc generate -f sql/sqlc.yaml

  makemigrations:
    desc: Make migrations
    vars:
      NAME: '{{default "" .NAME}}'
    cmd: atlas migrate diff {{.NAME}} --to file://sql/schema.sql --dir file://sql/migrations?format=golang-migrate --dev-url "docker://postgres/18/dev?search_path=public"

  build:
    desc: Build mkrepo
    aliases: [b]
    sources:
      - 'cmd/**/*'
      - 'internal/**/*'
      - 'sql/**/*'
      - 'static/**/*'
      - 'template/**/*'
      - 'go.mod'
      - 'go.sum'
    generates:
      - bin/mkrepo
    cmd: scripts/build.sh

  run:
    desc: Run server
    deps: [build]
    aliases: [r]
    cmd: bin/mkrepo server

  test:
    desc: Run tests
    aliases: [t]
    cmds:
      - go test -v ./...

  clean:
    desc: Clean up
    aliases: [c]
    cmds:
      - rm -rf bin
      - rm -rf .task
      - find . -name '__debug_*' -type f -delete

  docker:build:
    desc: Build Docker image
    cmd: scripts/docker-build.sh

  docker:push:
    desc: Push Docker image
    cmd: scripts/docker-push.sh

  release:
    desc: Release new version
    prompt: Do you want to release new version {{.VERSION}}?
    preconditions:
      - git diff-index --quiet HEAD --
    cmds:
      - git tag -a v{{.VERSION}} -m "Release {{.VERSION}}"
      - git push origin v{{.VERSION}}
