name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch tags
        run: git fetch --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod download

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Fmt Go code
        run: "[ ! $(task fmt) ]"

      - name: Vet Go code
        run: task vet

      - name: Lint Go code
        run: task lint

      - name: Vulnerability check
        run: task vulncheck

      - name: Build
        run: task build

      - name: Test
        run: task test

      - name: TMP
        run: git describe --tags --abbrev=0 | sed 's/^v//'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: task docker:build

      - name: Docker push
        run: task docker:build
