name: Go

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod download

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Go generate
        run: task generate

      - name: Fmt Go code
        run: "[ ! $(task fmt) ]"

      - name: Vet Go code
        run: task vet

      - name: Lint Go code
        run: task lint

      - name: Vulnerability check
        run: task vulncheck

      - name: Build
        run: task build

      - name: Test
        run: task test

  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [go]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: task docker:build

      - name: Docker push
        run: task docker:push
